// app/layout.js
import { Noto_Serif} from "next/font/google";
import "./globals.css";
import Header from "./components/header"
import Footer from "./components/footer"

const notosherif = Noto_Serif({
  subsets: ["latin"],
  variable: "--font-notosherif",   // creates CSS var --font-figtree
  weight: ["300","400","500","600","700","800"],
  display: "swap",
});

export const metadata = {
  title: "My Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // apply variable to <html> so it's available to :root and Tailwind
    <html lang="en" className={`${notosherif.variable} ${notosherif.className}`}>
      <body className="antialiased">
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
